-- MySQL Script generated by MySQL Workbench
-- Wed Jul  7 20:17:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema innova-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema innova-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `innova-db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `innova-db` ;

-- -----------------------------------------------------
-- Table `innova-db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `innova-db`.`users` (
  `user_type` VARCHAR(31) NOT NULL,
  `id` VARCHAR(255) NOT NULL,
  `is_active` BIT(1) NOT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `cellphone` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_6dotkott2kjsp8vw4d0m25fb7` (`email` ASC) VISIBLE,
  UNIQUE INDEX `UK_4i5v6uaqlmmx0bwui2gvgmftc` (`cellphone` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `innova-db`.`consultants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `innova-db`.`consultants` (
  `code` VARCHAR(255) NOT NULL,
  `id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_2iljx2bup7v0v1e0rtk2q2mfh` (`code` ASC) VISIBLE,
  CONSTRAINT `FKr01523mxgyc6q96skwno14yy9`
    FOREIGN KEY (`id`)
    REFERENCES `innova-db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `innova-db`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `innova-db`.`contacts` (
  `company_address` VARCHAR(255) NULL DEFAULT NULL,
  `company_cellphone` VARCHAR(255) NULL DEFAULT NULL,
  `company_city` VARCHAR(255) NULL DEFAULT NULL,
  `company_department` VARCHAR(255) NULL DEFAULT NULL,
  `company_email` VARCHAR(255) NULL DEFAULT NULL,
  `company_name` VARCHAR(255) NULL DEFAULT NULL,
  `company_phone` VARCHAR(255) NULL DEFAULT NULL,
  `company_website` VARCHAR(255) NULL DEFAULT NULL,
  `nit` VARCHAR(255) NULL DEFAULT NULL,
  `registration_date` DATE NOT NULL,
  `request_accompaniment` BIT(1) NOT NULL,
  `contact_type` INT NOT NULL,
  `user_type` VARCHAR(255) NULL DEFAULT NULL,
  `id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKrsreoqkkwxotk32qvnxu6hwuy`
    FOREIGN KEY (`id`)
    REFERENCES `innova-db`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `innova-db`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `innova-db`.`clients` (
  `birthdate` DATE NULL DEFAULT NULL,
  `birthplace` VARCHAR(255) NULL DEFAULT NULL,
  `commercial_register_number` VARCHAR(255) NULL DEFAULT NULL,
  `company_constitution_date` DATE NULL DEFAULT NULL,
  `company_legal_constitution` INT NULL DEFAULT NULL,
  `company_legal_representative` VARCHAR(255) NULL DEFAULT NULL,
  `company_number_of_direct_employees` SMALLINT NULL DEFAULT NULL,
  `company_number_of_employees` SMALLINT NULL DEFAULT NULL,
  `company_number_of_full_time_employees` SMALLINT NULL DEFAULT NULL,
  `company_number_of_indirect_employees` SMALLINT NULL DEFAULT NULL,
  `company_number_of_part_time_employees` SMALLINT NULL DEFAULT NULL,
  `company_sector` INT NULL DEFAULT NULL,
  `consultant_id` VARCHAR(255) NOT NULL,
  `contact_city` VARCHAR(255) NULL DEFAULT NULL,
  `contact_department` VARCHAR(255) NULL DEFAULT NULL,
  `contact_phone` VARCHAR(255) NULL DEFAULT NULL,
  `date_of_entry_company` DATE NULL DEFAULT NULL,
  `discovery_channel` INT NULL DEFAULT NULL,
  `educational_level` INT NULL DEFAULT NULL,
  `ethnic_group` INT NULL DEFAULT NULL,
  `gender` INT NULL DEFAULT NULL,
  `has_commercial_register` BIT(1) NULL DEFAULT NULL,
  `international_activity` INT NULL DEFAULT NULL,
  `international_activity_countries` VARCHAR(255) NULL DEFAULT NULL,
  `is_displaced` BIT(1) NULL DEFAULT NULL,
  `is_ecommerce` BIT(1) NULL DEFAULT NULL,
  `is_handicapped` BIT(1) NULL DEFAULT NULL,
  `last_year_of_renovation` DATE NULL DEFAULT NULL,
  `observations` LONGTEXT NULL DEFAULT NULL,
  `other_company_sector` VARCHAR(255) NULL DEFAULT NULL,
  `other_legal_constitution` VARCHAR(255) NULL DEFAULT NULL,
  `position_in_company` VARCHAR(255) NULL DEFAULT NULL,
  `principal_code_ciiu` VARCHAR(255) NULL DEFAULT NULL,
  `services_products_offered` LONGTEXT NULL DEFAULT NULL,
  `id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_bfa7cp39q74jjutdf46o2a502` (`contact_phone` ASC) VISIBLE,
  INDEX `FKd1clmng00er27b86eumc78opu` (`consultant_id` ASC) VISIBLE,
  CONSTRAINT `FKd1clmng00er27b86eumc78opu`
    FOREIGN KEY (`consultant_id`)
    REFERENCES `innova-db`.`consultants` (`id`),
  CONSTRAINT `FKlsj9hpupke3ohw43826jldnxp`
    FOREIGN KEY (`id`)
    REFERENCES `innova-db`.`contacts` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `innova-db`.`advisories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `innova-db`.`advisories` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `area` INT NOT NULL,
  `client_id` VARCHAR(255) NOT NULL,
  `consultant_id` VARCHAR(255) NOT NULL,
  `date` DATETIME NOT NULL,
  `duration_in_hours` TINYINT NULL DEFAULT NULL,
  `notes` LONGTEXT NULL DEFAULT NULL,
  `preparation_type_in_hours` TINYINT NULL DEFAULT NULL,
  `state` INT NOT NULL,
  `subject` VARCHAR(255) NOT NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKh9mno9l55470hxsteuk1jofh3` (`client_id` ASC) VISIBLE,
  INDEX `FKdyv1bqhjdjrw3rrhpuysoeoln` (`consultant_id` ASC) VISIBLE,
  CONSTRAINT `FKdyv1bqhjdjrw3rrhpuysoeoln`
    FOREIGN KEY (`consultant_id`)
    REFERENCES `innova-db`.`consultants` (`id`),
  CONSTRAINT `FKh9mno9l55470hxsteuk1jofh3`
    FOREIGN KEY (`client_id`)
    REFERENCES `innova-db`.`clients` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `innova-db`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `innova-db`.`events` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `close_date` DATETIME NOT NULL,
  `department` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `event_duration_in_hours` TINYINT NULL DEFAULT NULL,
  `link` VARCHAR(255) NULL DEFAULT NULL,
  `place` VARCHAR(255) NULL DEFAULT NULL,
  `registration_dead_line_date` DATE NOT NULL,
  `start_date` DATETIME NOT NULL,
  `state` INT NOT NULL,
  `theme` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `type` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `innova-db`.`inscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `innova-db`.`inscriptions` (
  `event_id` BIGINT NOT NULL,
  `user_id` VARCHAR(255) NOT NULL,
  `attended` BIT(1) NULL DEFAULT NULL,
  `inscription_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`event_id`, `user_id`),
  INDEX `FKgy22bjatqbltee1ktus2xvac8` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKgy22bjatqbltee1ktus2xvac8`
    FOREIGN KEY (`user_id`)
    REFERENCES `innova-db`.`contacts` (`id`),
  CONSTRAINT `FKkhxdv16tf8b8cc2pjoqmeuq04`
    FOREIGN KEY (`event_id`)
    REFERENCES `innova-db`.`events` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
